In [19]:
import pandas as pd
import numpy as np

# Read the CSV files
df1 = pd.read_csv('topten.csv')
df2 = pd.read_csv('shape.csv')

# Join the dataframes
df = pd.merge(df1, df2, on='geography')

# 'common_column' is the column that is common between df1 and df2.
# If there are multiple common columns, you can pass them as a list.
# For example: on=['column1', 'column2']

# Now, 'df' is a new dataframe that is the result of joining df1 and df2.

In [20]:
df

,geography,POPULATION,families_number,families_median_income,occupied_housing_units,median_monthly_costs_occupied_units,family_7_or_more_people,families_received_ssi_or_public_assistance,families_received_social_security,percent_below_poverty_level,...,TX_df_viable_2.HRCN_AFREQ,TX_df_viable_2.HRCN_EXPP,TX_df_viable_2.HRCN_RISKS,TX_df_viable_2.Heat_Wave___Hazard_Type_Risk_Index_Score,TX_df_viable_2.Drought___Hazard_Type_Risk_Index_Score,TX_df_viable_2.Crime_Rate,TX_df_viable_2.viability_score,TX_df_viable_2.geo_text,longitude_int,geoid
0,48201341600,0.222226,0.220348,0.412096,0.295060,0.40950,0.189845,0.135785,0.292442,0.068235,...,0.287101,0.222226,0.976631,0.759453,0.818979,0.126580,-0.269969,4.820134e+10,29.591970,NaN
1,48201232304,0.257061,0.217303,0.176156,0.249444,0.27650,0.167770,0.543140,0.147674,0.263529,...,0.237950,0.257060,0.950396,0.779352,0.785468,0.126580,-0.156221,4.820123e+10,29.858073,NaN
2,48167721902,0.193384,0.160472,0.271016,0.275256,0.28425,0.000000,0.305516,0.186047,0.184706,...,0.309352,0.193376,0.979917,0.899291,0.880255,0.070939,-0.204464,4.816772e+10,29.437695,NaN
3,48201340202,0.261962,0.268679,0.686252,0.306742,0.52850,0.209713,0.202263,0.249419,0.067059,...,0.276329,0.261962,0.979700,0.767754,0.871274,0.126580,-0.265197,4.820134e+10,29.613327,NaN
4,48201350500,0.235670,0.213878,0.362072,0.263017,0.34575,0.256071,0.473833,0.251744,0.118824,...,0.276329,0.235664,0.986983,0.757519,0.871202,0.126580,-0.168899,4.820135e+10,29.581667,NaN
5,48061012301,0.170535,0.170113,0.307224,0.192145,0.27425,0.006623,0.074965,0.340698,0.237647,...,0.215038,0.170535,0.938464,0.553006,0.922890,0.069931,-0.234494,4.806101e+10,26.158117,NaN
6,48201332600,0.217789,0.192059,0.186620,0.235759,0.20550,0.079470,0.311174,0.247093,0.192941,...,0.276329,0.217789,0.966714,0.758892,0.876425,0.126580,-0.167083,4.820133e+10,29.674989,NaN
7,48167725800,0.162721,0.187873,0.391084,0.252225,0.37225,0.048565,0.132956,0.297093,0.196471,...,0.739614,0.162708,0.954843,0.894298,0.000000,0.070939,-0.216951,4.816773e+10,29.283432,NaN
8,48201253602,0.156793,0.117849,0.000000,0.189364,0.24025,0.000000,0.363508,0.053488,0.397647,...,0.245407,0.156793,0.894392,0.762284,0.000000,0.126580,-0.169050,4.820125e+10,29.752277,NaN

In [21]:
# Read the CSV file
df3 = pd.read_csv('all.csv')
df4 = pd.merge(df3, df2, on='geography')

def get_coordinates(geoID):
    # Convert geoID to int or float if necessary
    try:
        geoID = int(geoID)
    except ValueError:
        try:
            geoID = float(geoID)
        except ValueError:
            pass

    row = df4[df4['geography'] == geoID]


    if len(row) > 0:
        return row['tl_2023_48_tract.INTPTLAT'].values[0], row['tl_2023_48_tract.INTPTLON'].values[0]
    else:
        return None

# User input
geoID = input("Please enter a geoID: ")

# Get coordinates
coordinates = get_coordinates(geoID)

if coordinates:
    print(f"The coordinates for geoID {geoID} are {coordinates}.")
else:
    print(f"No coordinates found for geoID {geoID}.")

Please enter a geoID: 48157674100
        geography  POPULATION  families_number  families_median_income  \
2099  48157674100    0.222921          0.21743                  0.4888

      occupied_housing_units  median_monthly_costs_occupied_units  \
2099                0.266578                                0.364

      family_7_or_more_people  families_received_ssi_or_public_assistance  \
2099                      0.0                                     0.15983

      families_received_social_security  percent_below_poverty_level  ...  \
2099                           0.271512                         0.08  ...

      TX_df_viable_2.HRCN_AFREQ  TX_df_viable_2.HRCN_EXPP  \
2099                   0.230274                  0.222921

      TX_df_viable_2.HRCN_RISKS  \
2099                   0.927988

      TX_df_viable_2.Heat_Wave___Hazard_Type_Risk_Index_Score  \
2099                                           0.303394

      TX_df_viable_2.Drought___Hazard_Type_Risk_Index_Score  \
2099                                           0.725774

      TX_df_viable_2.Crime_Rate  TX_df_viable_2.viability_score  \
2099                   0.036623                       -0.020322

      TX_df_viable_2.geo_text  longitude_int  geoid
2099             4.815767e+10      29.579169    NaN

[1 rows x 65 columns]
The coordinates for geoID 48157674100 are (29.5791692, -95.5995891).

In [22]:
df4

,geography,POPULATION,families_number,families_median_income,occupied_housing_units,median_monthly_costs_occupied_units,family_7_or_more_people,families_received_ssi_or_public_assistance,families_received_social_security,percent_below_poverty_level,...,TX_df_viable_2.HRCN_AFREQ,TX_df_viable_2.HRCN_EXPP,TX_df_viable_2.HRCN_RISKS,TX_df_viable_2.Heat_Wave___Hazard_Type_Risk_Index_Score,TX_df_viable_2.Drought___Hazard_Type_Risk_Index_Score,TX_df_viable_2.Crime_Rate,TX_df_viable_2.viability_score,TX_df_viable_2.geo_text,longitude_int,geoid
0,48201341600,0.222226,0.220348,0.412096,0.295060,0.40950,0.189845,0.135785,0.292442,0.068235,...,0.287101,0.222226,0.976631,0.759453,0.818979,0.126580,-0.269969,4.820134e+10,29.591970,NaN
1,48201232304,0.257061,0.217303,0.176156,0.249444,0.27650,0.167770,0.543140,0.147674,0.263529,...,0.237950,0.257060,0.950396,0.779352,0.785468,0.126580,-0.156221,4.820123e+10,29.858073,NaN
2,48167721902,0.193384,0.160472,0.271016,0.275256,0.28425,0.000000,0.305516,0.186047,0.184706,...,0.309352,0.193376,0.979917,0.899291,0.880255,0.070939,-0.204464,4.816772e+10,29.437695,NaN
3,48201340202,0.261962,0.268679,0.686252,0.306742,0.52850,0.209713,0.202263,0.249419,0.067059,...,0.276329,0.261962,0.979700,0.767754,0.871274,0.126580,-0.265197,4.820134e+10,29.613327,NaN
4,48201350500,0.235670,0.213878,0.362072,0.263017,0.34575,0.256071,0.473833,0.251744,0.118824,...,0.276329,0.235664,0.986983,0.757519,0.871202,0.126580,-0.168899,4.820135e+10,29.581667,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6878,48381020100,0.071459,0.078777,0.452736,0.097686,0.25075,0.059603,0.000000,0.135465,0.037647,...,NaN,NaN,NaN,0.206244,0.000000,0.011020,0.023236,4.838102e+10,35.179733,NaN
6879,48381021605,0.064737,0.082710,0.479544,0.107254,0.28100,0.000000,0.021216,0.081395,0.017647,...,NaN,NaN,NaN,0.205671,0.000000,0.011020,0.020510,4.838102e+10,35.153649,NaN
6880,48441013000,0.019968,0.007992,1.000000,0.007454,0.57300,0.000000,0.000000,0.003488,0.000000,...,0.013134,0.019968,0.173467,0.297411,0.701566,0.072588,-0.057901,4.844101e+10,32.423876,NaN
6881,48381020400,0.064638,0.075986,0.554724,0.094348,0.35425,0.000000,0.000000,0.119767,0.037647,...,NaN,NaN,NaN,0.200272,0.000000,0.011020,0.017788,4.838102e+10,35.178355,NaN
6882,48303010411,0.046260,0.034251,0.351428,0.064085,0.33350,0.000000,0.000000,0.019186,0.000000,...,0.013134,0.046260,0.045389,0.211177,0.000000,0.144640,0.011559,4.830301e+10,33.508813,NaN

In [23]:
import numpy as np

def haversine(lat1, lon1, lat2, lon2):
    # Convert degrees to radians
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlon = lon2 - lon1
    dlat = lat2 - lat1
    a = np.sin(dlat/2.0)**2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a))
    r = 6371  # Radius of earth in kilometers
    return c * r

In [25]:
# User's coordinates
user_lat, user_lon = coordinates  # replace with actual coordinates

# Initialize variables to store the minimum distance and index
min_distance = np.inf
min_index = None

# Loop through the DataFrame
for i, row in df.iterrows():
    # Calculate the distance
    distance = haversine(user_lat, user_lon, row['tl_2023_48_tract.INTPTLAT'], row['tl_2023_48_tract.INTPTLON'])

    # If the distance is less than the current minimum, update the minimum distance and index
    if distance < min_distance:
        min_distance = distance
        min_index = i

# Print the index of the closest coordinates
print(f"The closest coordinates are at index {min_index} with a distance of {min_distance} kilometers.")

The closest coordinates are at index 6 with a distance of 30.238553453050113 kilometers.

In [27]:
df.loc[[min_index]]

,geography,POPULATION,families_number,families_median_income,occupied_housing_units,median_monthly_costs_occupied_units,family_7_or_more_people,families_received_ssi_or_public_assistance,families_received_social_security,percent_below_poverty_level,...,TX_df_viable_2.HRCN_AFREQ,TX_df_viable_2.HRCN_EXPP,TX_df_viable_2.HRCN_RISKS,TX_df_viable_2.Heat_Wave___Hazard_Type_Risk_Index_Score,TX_df_viable_2.Drought___Hazard_Type_Risk_Index_Score,TX_df_viable_2.Crime_Rate,TX_df_viable_2.viability_score,TX_df_viable_2.geo_text,longitude_int,geoid
6,48201332600,0.217789,0.192059,0.18662,0.235759,0.2055,0.07947,0.311174,0.247093,0.192941,...,0.276329,0.217789,0.966714,0.758892,0.876425,0.12658,-0.167083,4.820133e+10,29.674989,NaN